-- AlterTable
ALTER TABLE `MatchLog` MODIFY `type` ENUM('MATCH_CREATED', 'MATCH_START', 'MATCH_UPDATE', 'MATCH_END', 'MATCH_DELETE', 'MATCH_RESET', 'MATCH_PAUSED', 'MATCH_RESUMED', 'PLAYER_JOINED', 'PLAYER_ADDED_LIST', 'PLAYER_LEFT', 'REMOVE_PLAYER', 'REMOVE_LIST', 'ROUND_END', 'UNIT_DAMAGE', 'UNIT_DAMAGE_REMOVED', 'UNIT_HEAT', 'UNIT_CRIT', 'UNIT_CRIT_REMOVED', 'HEARTBEAT') NOT NULL;
