-- AlterTable
ALTER TABLE `MatchLog` MODIFY `type` ENUM('MATCH_CREATED', 'MATCH_START', 'MATCH_UPDATE', 'MATCH_END', 'MATCH_DELETE', 'MATCH_RESET', 'MATCH_PAUSED', 'MATCH_RESUMED', 'PLAYER_JOINED', 'PLAYER_ADDED_LIST', 'PLAYER_LEFT', 'REMOVE_PLAYER', 'REMOVE_LIST', 'ROUND_END', 'UNIT_DAMAGE', 'UNIT_DAMAGE_REMOVED', 'UNIT_HEAT', 'UNIT_CRIT', 'UNIT_CRIT_REMOVED', 'HEARTBEAT', 'BFS_USED', 'BFS_RESTORED') NOT NULL;

-- CreateTable
CREATE TABLE `MatchBFS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `listId` INTEGER NOT NULL,
    `bfsId` INTEGER NOT NULL,
    `count` INTEGER NOT NULL,
    `used` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `MatchBFS` ADD CONSTRAINT `MatchBFS_listId_fkey` FOREIGN KEY (`listId`) REFERENCES `MatchList`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
