import { form, query } from "$app/server";
import { getGeneralId } from "$lib/remote/era-faction.remote";
import { getMULDataFromId, getMULDataFromName, isAvailable, isUnique } from "$lib/remote/unit.remote";
import type { MulUnit } from "$lib/types/listTypes";
import { getDocument } from "pdfjs-dist";
import { getUnitDataFromPDF } from "./parse";
import { prisma } from "$lib/server/prisma";
import { getNewSkillCost } from "$lib/utilities/genericBattletechUtilities";

export type ValidationUnitData = {
	id: string;
	name: string;
	mulData?: MulUnit;
	available?: boolean;
	unique?: boolean;
	skill: number;
	pv: number;
	link?: string;
};

export const getUnitData = form(async (data) => {
	const fileData = data.get("listFile") as File;
	const era = Number(data.get("selectedEra")?.toString());
	const faction = Number(data.get("selectedFaction")?.toString());
	let unitData: ValidationUnitData[] = [];

	const buffer = await fileData.arrayBuffer();
	const pdf = await getDocument(buffer).promise;
	const metadata = (await pdf.getMetadata()).info;
	const page = await pdf.getPage(1);
	const content = await page.getTextContent();

	const parsedData = getUnitDataFromPDF(content, metadata);

	if (parsedData.status == "failed")
		return { status: "failed", message: "Invalid PDF Format. Either it wasn't generated by the MUL or this site, or my reader is broken somehow." };
	if (parsedData.status == "ongoing")
		return { status: "failed", message: "PDF format will be supported soon, but is currently in progress. Please upload a pdf generated from the MUL" };

	for (const parsedUnit of parsedData.data ?? []) {
		const unit = await getMULDataFromName(parsedUnit.name);
		if (unit?.status == "success") {
			let unique: boolean | undefined, available: boolean | undefined;
			if (unit) {
				unique = await isUnique({ mulId: unit.data!.mulId, era });
				const general = (await getGeneralId({ era, faction }))?.general;
				available = await isAvailable({ mulId: unit.data!.mulId, eras: [era], factions: [faction, general ?? 0] });
			}

			unitData.push({
				id: crypto.randomUUID(),
				name: parsedUnit.name,
				skill: parsedUnit.skill,
				pv: parsedUnit.pv,
				mulData: unit.data,
				link: unit ? `http://masterunitlist.info/Unit/Details/${unit.data!.mulId}` : undefined,
				unique: unique,
				available: available
			});
		}
	}
	await nothing().refresh();
	return { status: "success", data: unitData };
});

export const getPossibleUnitList = form(async (data) => {
	const searchTerm = data.get("searchTerm")?.toString();
	const results = await prisma.unit.findMany({ where: { name: { contains: searchTerm } }, select: { mulId: true, name: true } });

	await nothing().refresh();
	return results;
});

export const fixUnitData = form(async (data) => {
	const mulId = Number(data.get("selectedUnitId")?.toString());
	const mulData = await getMULDataFromId(mulId);
	if (mulData.status == "failed") return { status: "failed", message: "Unit data not found" };

	const skill = Number(data.get("unitSkill")?.toString());
	const era = Number(data.get("era")?.toString());
	const faction = Number(data.get("faction")?.toString());

	await nothing().refresh();
	if (mulData == undefined) {
		return { status: "failed", message: "Invalid Unit Id" };
	} else {
		const unique = await isUnique({ mulId: mulId, era });
		const general = (await getGeneralId({ era, faction }))?.general;
		const available = await isAvailable({ mulId: mulId, eras: [era], factions: [faction, general ?? 0] });

		let unitData: ValidationUnitData = {
			id: crypto.randomUUID(),
			name: mulData.data!.name,
			skill,
			pv: getNewSkillCost(skill, mulData.data!.pv),
			mulData: mulData.data,
			link: `http://masterunitlist.info/Unit/Details/${mulData.data!.mulId}`,
			unique,
			available
		};
		return { status: "success", data: unitData };
	}
});

export const nothing = query(async () => {});
